export const MODULE_EVENT_MAP = {
  M23: ['SECURITY.ACCESS_DENIED','SECURITY.CROSS_TENANT_ATTEMPT','SECURITY.POLICY_CHANGED'],
  M24: ['CACHE.INVALIDATED','PERFORMANCE.SLOW_OPERATION','PERFORMANCE.THRESHOLD_EXCEEDED'],
  M25: ['NOTIFICATION.CREATED','NOTIFICATION.SENT','NOTIFICATION.FAILED','EVENT.PUBLISHED'],
  M26: ['SEARCH.INDEXED','SEARCH.INDEX_DELETED','SEARCH.REBUILD_COMPLETED'],
  M27: ['KPI.THRESHOLD_BREACHED','DASHBOARD.UPDATED','ANALYTICS.REFRESHED'],
  M28: ['REPORT.GENERATED','REPORT.EXPORTED','REPORT.DELIVERY_FAILED','COMMUNICATION.SENT'],
  M29: ['MOBILE.SESSION_CREATED','SYNC.QUEUED','SYNC.COMPLETED','SYNC.CONFLICT','SYNC.FAILED'],
  M30: ['AI.RECOMMENDATION_CREATED','AI.CLASSIFICATION_CREATED','AI.FRAUD_ALERT','INTEGRATION.REQUEST_FAILED'],
  M31: ['TALENT.MATCHED','SKILL.GAP.DETECTED','CANDIDATE.FEEDBACK.RECORDED','INTERVIEW.SCORED'],
  M32: ['WORKFLOW.STARTED','WORKFLOW.COMPLETED','WORKFLOW.FAILED','APPROVAL.REQUESTED','APPROVAL.APPROVED','APPROVAL.REJECTED'],
  M33: ['INTEGRATION.CONNECTED','INTEGRATION.DISCONNECTED','WEBHOOK.RECEIVED','WEBHOOK.REJECTED','DEAD_LETTER.CREATED'],
  M34: ['SUBSCRIPTION.ACTIVATED','SUBSCRIPTION.SUSPENDED','SUBSCRIPTION.EXPIRED','PLAN.CHANGED','QUOTA.WARNING','QUOTA.EXCEEDED'],
} as const;
